version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn package –DskipTests
      - mv target/*.jar hotel-room-reservation.jar
artifacts:
  files:
      - hotel-room-reservation.jar